services:
    valkey:
        healthcheck:
            test:
                - CMD
                - 'false'
            interval: 1s
            timeout: 1s
            retries: 1
            start_period: 0s
