/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { petStatusSchema } from './petStatusSchema'

export const createPetSchema = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(120)),
    get status() {
        return z.optional(petStatusSchema)
    },
})

export type CreatePetSchema = z.infer<typeof createPetSchema>
