/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type * as z from 'zod/mini'

import {
    createPetMutationRequestSchema,
    createPet201Schema,
    createPet422Schema,
    createPetMutationResponseSchema,
} from './petsController/createPetSchema'
import {
    deletePet204Schema,
    deletePet404Schema,
    deletePetMutationResponseSchema,
    deletePetPathParamsSchema,
} from './petsController/deletePetSchema'
import {
    findPetsByStatus200Schema,
    findPetsByStatus422Schema,
    findPetsByStatusQueryResponseSchema,
    findPetsByStatusQueryParamsSchema,
} from './petsController/findPetsByStatusSchema'
import {
    getPetById200Schema,
    getPetById404Schema,
    getPetByIdQueryResponseSchema,
    getPetByIdPathParamsSchema,
} from './petsController/getPetByIdSchema'
import {
    updatePetMutationRequestSchema,
    updatePet200Schema,
    updatePet404Schema,
    updatePet422Schema,
    updatePetMutationResponseSchema,
    updatePetPathParamsSchema,
} from './petsController/updatePetSchema'

export type OperationSchema = {
    readonly request: z.ZodTypeAny | undefined
    readonly parameters: {
        readonly path: z.ZodTypeAny | undefined
        readonly query: z.ZodTypeAny | undefined
        readonly header: z.ZodTypeAny | undefined
    }
    readonly responses: {
        readonly [status: number]: z.ZodTypeAny
        readonly default: z.ZodTypeAny
    }
    readonly errors: {
        readonly [status: number]: z.ZodTypeAny
    }
}

export type OperationsMap = Record<string, OperationSchema>

export const operations = {
    findPetsByStatus: {
        request: undefined,
        parameters: {
            path: undefined,
            query: findPetsByStatusQueryParamsSchema,
            header: undefined,
        },
        responses: {
            200: findPetsByStatus200Schema,
            422: findPetsByStatus422Schema,
            default: findPetsByStatusQueryResponseSchema,
        },
        errors: {
            422: findPetsByStatus422Schema,
        },
    },
    createPet: {
        request: createPetMutationRequestSchema,
        parameters: {
            path: undefined,
            query: undefined,
            header: undefined,
        },
        responses: {
            201: createPet201Schema,
            422: createPet422Schema,
            default: createPetMutationResponseSchema,
        },
        errors: {
            422: createPet422Schema,
        },
    },
    getPetById: {
        request: undefined,
        parameters: {
            path: getPetByIdPathParamsSchema,
            query: undefined,
            header: undefined,
        },
        responses: {
            200: getPetById200Schema,
            404: getPetById404Schema,
            default: getPetByIdQueryResponseSchema,
        },
        errors: {
            404: getPetById404Schema,
        },
    },
    updatePet: {
        request: updatePetMutationRequestSchema,
        parameters: {
            path: updatePetPathParamsSchema,
            query: undefined,
            header: undefined,
        },
        responses: {
            200: updatePet200Schema,
            404: updatePet404Schema,
            422: updatePet422Schema,
            default: updatePetMutationResponseSchema,
        },
        errors: {
            404: updatePet404Schema,
            422: updatePet422Schema,
        },
    },
    deletePet: {
        request: undefined,
        parameters: {
            path: deletePetPathParamsSchema,
            query: undefined,
            header: undefined,
        },
        responses: {
            204: deletePet204Schema,
            404: deletePet404Schema,
            default: deletePetMutationResponseSchema,
        },
        errors: {
            404: deletePet404Schema,
        },
    },
} as const

export const paths = {
    '/pets': {
        get: operations['findPetsByStatus'],
        post: operations['createPet'],
    },
    '/pets/{petId}': {
        get: operations['getPetById'],
        patch: operations['updatePet'],
        delete: operations['deletePet'],
    },
} as const
