/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { petSchema } from './petSchema'

export const petPageSchema = z.object({
    get items() {
        return z.array(petSchema)
    },
    offset: z.int().check(z.minimum(0)),
    limit: z.int().check(z.minimum(1), z.maximum(100)),
    total: z.int().check(z.minimum(0)),
})

export type PetPageSchema = z.infer<typeof petPageSchema>
