/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { petStatusSchema } from './petStatusSchema'

export const petSchema = z.object({
    id: z.string().check(z.minLength(1)),
    name: z.string().check(z.minLength(1), z.maxLength(120)),
    get status() {
        return petStatusSchema
    },
    createdAt: z.coerce.date(),
})

export type PetSchema = z.infer<typeof petSchema>
