/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

/** Current lifecycle status of a pet. */
export const petStatusSchema = z.enum(['available', 'pending', 'sold'])

export type PetStatusSchema = z.infer<typeof petStatusSchema>
