/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

export const problemSchema = z.object({
    status: z.int().check(z.minimum(400), z.maximum(599)),
    code: z.string().check(z.minLength(1)),
    title: z.string().check(z.minLength(1)),
    detail: z.optional(z.string()),
})

export type ProblemSchema = z.infer<typeof problemSchema>
