/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { petStatusSchema } from './petStatusSchema'

export const updatePetSchema = z.object({
    name: z.optional(z.string().check(z.minLength(1), z.maxLength(120))),
    get status() {
        return z.optional(petStatusSchema)
    },
})

export type UpdatePetSchema = z.infer<typeof updatePetSchema>
