/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export const operations = {
    findPetsByStatus: {
        path: '/pets',
        method: 'get',
    },
    createPet: {
        path: '/pets',
        method: 'post',
    },
    getPetById: {
        path: '/pets/:petId',
        method: 'get',
    },
    updatePet: {
        path: '/pets/:petId',
        method: 'patch',
    },
    deletePet: {
        path: '/pets/:petId',
        method: 'delete',
    },
}
