/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { PetStatus } from './PetStatus'

export type CreatePet = {
    /**
     * @type string
     * @minLength 1
     * @maxLength 120
     */
    name: string
    /** @default 'available' */
    status?: PetStatus
}
