/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { PetStatus } from './PetStatus'

export type Pet = {
    /**
     * @type string
     * @minLength 1
     */
    id: string
    /**
     * @type string
     * @minLength 1
     * @maxLength 120
     */
    name: string
    /**
     * Current lifecycle status of a pet.
     *
     * @type string
     */
    status: PetStatus
    /** @type string, date-time */
    createdAt: Date
}
