/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Pet } from './Pet'

export type PetPage = {
    /** @type array */
    items: Pet[]
    /**
     * @type integer
     * @minLength 0
     */
    offset: number
    /**
     * @type integer
     * @minLength 1
     * @maxLength 100
     */
    limit: number
    /**
     * @type integer
     * @minLength 0
     */
    total: number
}
