/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export const petStatusEnum = {
    available: 'available',
    pending: 'pending',
    sold: 'sold',
} as const

export type PetStatusEnumKey = (typeof petStatusEnum)[keyof typeof petStatusEnum]

/**
 * Current lifecycle status of a pet.
 *
 * @example
 *     available
 */
export type PetStatus = PetStatusEnumKey

export const petStatusEnum2 = {
    available: 'available',
    pending: 'pending',
    sold: 'sold',
} as const

export type PetStatusEnum2Key = (typeof petStatusEnum2)[keyof typeof petStatusEnum2]
