/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export type Problem = {
    /**
     * @type integer
     * @minLength 400
     * @maxLength 599
     */
    status: number
    /**
     * @type string
     * @minLength 1
     */
    code: string
    /**
     * @type string
     * @minLength 1
     */
    title: string
    /** @type string | undefined */
    detail?: string
}
