/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { PetStatus } from './PetStatus'

export type UpdatePet = {
    /**
     * @type string | undefined
     * @minLength 1
     * @maxLength 120
     */
    name?: string
    /**
     * Current lifecycle status of a pet.
     *
     * @type string | undefined
     */
    status?: PetStatus
}
