/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { PetStatus } from '../models/PetStatus'

import { faker } from '@faker-js/faker'

/** Current lifecycle status of a pet. */
export function createPetStatus(data?: Partial<PetStatus>): PetStatus {
    faker.seed([100])
    return data || faker.helpers.arrayElement<PetStatus>(['available', 'pending', 'sold'])
}
