/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { UpdatePet } from '../models/UpdatePet'

import { faker } from '@faker-js/faker'

import { createPetStatus } from './createPetStatus'

export function createUpdatePet(data?: Partial<UpdatePet>): UpdatePet {
    faker.seed([100])
    return {
        ...{
            name: faker.string.alpha({ length: { min: 1, max: 120 } }),
            get status() {
                return createPetStatus()
            },
            ...(data || {}),
        },
    }
}
