/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { CreatePet } from '../models/CreatePet'

import { faker } from '@faker-js/faker'

import { createPetStatus } from './createPetStatus'

export function createCreatePet(data?: Partial<CreatePet>): CreatePet {
    faker.seed([100])
    return {
        ...{
            name: faker.string.alpha({ length: { min: 1, max: 120 } }),
            get status() {
                return createPetStatus()
            },
            ...(data || {}),
        },
    }
}
