/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Problem } from '../models/Problem'

import { faker } from '@faker-js/faker'

export function createProblem(data?: Partial<Problem>): Problem {
    faker.seed([100])
    return {
        ...{
            status: faker.number.int({ min: 400, max: 599 }),
            code: faker.string.alpha({ length: 1 }),
            title: faker.string.alpha({ length: 1 }),
            detail: faker.string.alpha(),
        },
        ...(data || {}),
    }
}
