/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { PetPage } from '../models/PetPage'

import { faker } from '@faker-js/faker'

import { createPet } from './createPet'

export function createPetPage(data?: Partial<PetPage>): PetPage {
    faker.seed([100])
    return {
        ...{
            get items() {
                return faker.helpers.multiple(() => createPet())
            },
            offset: faker.number.int({ min: 0 }),
            limit: faker.number.int({ min: 1, max: 100 }),
            total: faker.number.int({ min: 0 }),
            ...(data || {}),
        },
    }
}
