/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Pet } from '../models/Pet'

import { faker } from '@faker-js/faker'

import { createPetStatus } from './createPetStatus'

export function createPet(data?: Partial<Pet>): Pet {
    faker.seed([100])
    return {
        ...{
            id: faker.string.alpha({ length: 1 }),
            name: faker.string.alpha({ length: { min: 1, max: 120 } }),
            get status() {
                return createPetStatus()
            },
            createdAt: faker.date.anytime(),
            ...(data || {}),
        },
    }
}
