/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { MockRoute } from '../mock-client'

import { createCreatePetMutationResponse } from './mocks/petsService/createCreatePet'
import { createDeletePetMutationResponse } from './mocks/petsService/createDeletePet'
import { createFindPetsByStatusQueryResponse } from './mocks/petsService/createFindPetsByStatus'
import { createGetPetByIdQueryResponse } from './mocks/petsService/createGetPetById'
import { createUpdatePetMutationResponse } from './mocks/petsService/createUpdatePet'

export const mockRoutes = [
    { method: 'GET', pattern: /^\/pets$/, create: createFindPetsByStatusQueryResponse },
    { method: 'POST', pattern: /^\/pets$/, status: 201, create: createCreatePetMutationResponse },
    { method: 'GET', pattern: /^\/pets\/[^/]+$/, create: createGetPetByIdQueryResponse },
    { method: 'PATCH', pattern: /^\/pets\/[^/]+$/, create: createUpdatePetMutationResponse },
    {
        method: 'DELETE',
        pattern: /^\/pets\/[^/]+$/,
        status: 204,
        create: createDeletePetMutationResponse,
    },
] satisfies MockRoute[]
