// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client'
import type {
    CreatePetData,
    CreatePetErrors,
    CreatePetResponses,
    DeletePetData,
    DeletePetErrors,
    DeletePetResponses,
    FindPetsByStatusData,
    FindPetsByStatusErrors,
    FindPetsByStatusResponses,
    GetPetByIdData,
    GetPetByIdErrors,
    GetPetByIdResponses,
    UpdatePetData,
    UpdatePetErrors,
    UpdatePetResponses,
} from './types.gen'

import { client } from './client.gen'
import {
    zCreatePetResponse,
    zDeletePetResponse,
    zFindPetsByStatusResponse,
    zGetPetByIdResponse,
    zUpdatePetResponse,
} from './zod.gen'

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of individual options.
     * This might be also useful if you want to implement a custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be used to access values
     * that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Find pets by status
 *
 * Returns one offset-based page of pets, optionally filtered by status.
 */
export const findPetsByStatus = <ThrowOnError extends boolean = false>(
    options?: Options<FindPetsByStatusData, ThrowOnError>,
): RequestResult<FindPetsByStatusResponses, FindPetsByStatusErrors, ThrowOnError> =>
    (options?.client ?? client).get<
        FindPetsByStatusResponses,
        FindPetsByStatusErrors,
        ThrowOnError
    >({
        responseValidator: async (data) => await zFindPetsByStatusResponse.parseAsync(data),
        url: '/pets',
        ...options,
    })

/**
 * Create a pet
 *
 * Adds one pet to the example catalog.
 */
export const createPet = <ThrowOnError extends boolean = false>(
    options: Options<CreatePetData, ThrowOnError>,
): RequestResult<CreatePetResponses, CreatePetErrors, ThrowOnError> =>
    (options.client ?? client).post<CreatePetResponses, CreatePetErrors, ThrowOnError>({
        responseValidator: async (data) => await zCreatePetResponse.parseAsync(data),
        url: '/pets',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

/**
 * Delete a pet
 *
 * Removes one pet from the example catalog.
 */
export const deletePet = <ThrowOnError extends boolean = false>(
    options: Options<DeletePetData, ThrowOnError>,
): RequestResult<DeletePetResponses, DeletePetErrors, ThrowOnError> =>
    (options.client ?? client).delete<DeletePetResponses, DeletePetErrors, ThrowOnError>({
        responseValidator: async (data) => await zDeletePetResponse.parseAsync(data),
        url: '/pets/{petId}',
        ...options,
    })

/**
 * Get a pet
 *
 * Returns one pet by its stable identifier.
 */
export const getPetById = <ThrowOnError extends boolean = false>(
    options: Options<GetPetByIdData, ThrowOnError>,
): RequestResult<GetPetByIdResponses, GetPetByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetPetByIdResponses, GetPetByIdErrors, ThrowOnError>({
        responseValidator: async (data) => await zGetPetByIdResponse.parseAsync(data),
        url: '/pets/{petId}',
        ...options,
    })

/**
 * Update a pet
 *
 * Partially updates the name or status of one pet.
 */
export const updatePet = <ThrowOnError extends boolean = false>(
    options: Options<UpdatePetData, ThrowOnError>,
): RequestResult<UpdatePetResponses, UpdatePetErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdatePetResponses, UpdatePetErrors, ThrowOnError>({
        responseValidator: async (data) => await zUpdatePetResponse.parseAsync(data),
        url: '/pets/{petId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })
