// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {})
}

export type Pet = Pet2

export type PetStatus = PetStatus3

export type PetPage = PetPage2

export type CreatePet = CreatePet2

export type UpdatePet = UpdatePet2

export type Problem = Problem2

/** Current lifecycle status of a pet. */
export const PetStatus = {
    AVAILABLE: 'available',
    PENDING: 'pending',
    SOLD: 'sold',
} as const

/** Current lifecycle status of a pet. */
export type PetStatus3 = (typeof PetStatus)[keyof typeof PetStatus]

export type Pet2 = {
    id: string
    name: string
    status: PetStatus3
    createdAt: string
}

export type PetPage2 = {
    items: Array<Pet2>
    offset: number
    limit: number
    total: number
}

export type Problem2 = {
    status: number
    code: string
    title: string
    detail?: string
}

export type CreatePet2 = {
    name: string
    status?: PetStatus3
}

export type UpdatePet2 = {
    name?: string
    status?: PetStatus3
}

/** Stable pet identifier. */
export type PetId = string

/** Return pets matching any supplied status. */
export type PetStatusFilter = Array<PetStatus3>

/** Zero-based collection offset. */
export type Offset = number

/** Maximum number of pets returned in one page. */
export type Limit = number

/** Return pets matching any supplied status. */
export type PetStatus2 = Array<PetStatus3>

/** Zero-based collection offset. */
export type Offset2 = number

/** Maximum number of pets returned in one page. */
export type Limit2 = number

/** Stable pet identifier. */
export type PetId2 = string

export type FindPetsByStatusData = {
    body?: never
    path?: never
    query?: {
        /** Return pets matching any supplied status. */
        status?: Array<PetStatus3>
        /** Zero-based collection offset. */
        offset?: number
        /** Maximum number of pets returned in one page. */
        limit?: number
    }
    url: '/pets'
}

export type FindPetsByStatusErrors = {
    /** The request does not satisfy the contract. */
    422: Problem2
}

export type FindPetsByStatusError = FindPetsByStatusErrors[keyof FindPetsByStatusErrors]

export type FindPetsByStatusResponses = {
    /** One page of pets. */
    200: PetPage2
}

export type FindPetsByStatusResponse = FindPetsByStatusResponses[keyof FindPetsByStatusResponses]

export type CreatePetData = {
    body: CreatePet2
    path?: never
    query?: never
    url: '/pets'
}

export type CreatePetErrors = {
    /** The request does not satisfy the contract. */
    422: Problem2
}

export type CreatePetError = CreatePetErrors[keyof CreatePetErrors]

export type CreatePetResponses = {
    /** The created pet. */
    201: Pet2
}

export type CreatePetResponse = CreatePetResponses[keyof CreatePetResponses]

export type DeletePetData = {
    body?: never
    path: {
        /** Stable pet identifier. */
        petId: string
    }
    query?: never
    url: '/pets/{petId}'
}

export type DeletePetErrors = {
    /** The requested pet does not exist. */
    404: Problem2
}

export type DeletePetError = DeletePetErrors[keyof DeletePetErrors]

export type DeletePetResponses = {
    /** The pet was deleted. */
    204: void
}

export type DeletePetResponse = DeletePetResponses[keyof DeletePetResponses]

export type GetPetByIdData = {
    body?: never
    path: {
        /** Stable pet identifier. */
        petId: string
    }
    query?: never
    url: '/pets/{petId}'
}

export type GetPetByIdErrors = {
    /** The requested pet does not exist. */
    404: Problem2
}

export type GetPetByIdError = GetPetByIdErrors[keyof GetPetByIdErrors]

export type GetPetByIdResponses = {
    /** The requested pet. */
    200: Pet2
}

export type GetPetByIdResponse = GetPetByIdResponses[keyof GetPetByIdResponses]

export type UpdatePetData = {
    body: UpdatePet2
    path: {
        /** Stable pet identifier. */
        petId: string
    }
    query?: never
    url: '/pets/{petId}'
}

export type UpdatePetErrors = {
    /** The requested pet does not exist. */
    404: Problem2
    /** The request does not satisfy the contract. */
    422: Problem2
}

export type UpdatePetError = UpdatePetErrors[keyof UpdatePetErrors]

export type UpdatePetResponses = {
    /** The updated pet. */
    200: Pet2
}

export type UpdatePetResponse = UpdatePetResponses[keyof UpdatePetResponses]
