// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/** Current lifecycle status of a pet. */
export const zPetStatus = z.enum(['available', 'pending', 'sold'])

export const zPetStatus2 = zPetStatus

export const zPet = z.object({
    id: z.string().min(1),
    name: z.string().min(1).max(120),
    status: zPetStatus,
    createdAt: z.iso.datetime(),
})

export const zPet2 = zPet

export const zPetPage = z.object({
    items: z.array(zPet),
    offset: z.int().gte(0),
    limit: z.int().gte(1).lte(100),
    total: z.int().gte(0),
})

export const zPetPage2 = zPetPage

export const zProblem = z.object({
    status: z.int().gte(400).lte(599),
    code: z.string().min(1),
    title: z.string().min(1),
    detail: z.string().optional(),
})

export const zProblem2 = zProblem

export const zCreatePet = z.object({
    name: z.string().min(1).max(120),
    status: zPetStatus.optional().default('available'),
})

export const zCreatePet2 = zCreatePet

export const zUpdatePet = z.object({
    name: z.string().min(1).max(120).optional(),
    status: zPetStatus.optional(),
})

export const zUpdatePet2 = zUpdatePet

/** Stable pet identifier. */
export const zPetId = z.string().min(1)

/** Return pets matching any supplied status. */
export const zPetStatusFilter = z.array(zPetStatus)

/** Zero-based collection offset. */
export const zOffset = z.int().gte(0).default(0)

/** Maximum number of pets returned in one page. */
export const zLimit = z.int().gte(1).lte(100).default(20)

/** Return pets matching any supplied status. */
export const zPetStatus3 = z.array(zPetStatus)

/** Zero-based collection offset. */
export const zOffset2 = z.int().gte(0).default(0)

/** Maximum number of pets returned in one page. */
export const zLimit2 = z.int().gte(1).lte(100).default(20)

/** Stable pet identifier. */
export const zPetId2 = z.string().min(1)

export const zFindPetsByStatusQuery = z.object({
    status: z.array(zPetStatus).optional(),
    offset: z.int().gte(0).optional().default(0),
    limit: z.int().gte(1).lte(100).optional().default(20),
})

/** One page of pets. */
export const zFindPetsByStatusResponse = zPetPage

export const zCreatePetBody = zCreatePet

/** The created pet. */
export const zCreatePetResponse = zPet

export const zDeletePetPath = z.object({
    petId: z.string().min(1),
})

/** The pet was deleted. */
export const zDeletePetResponse = z.void()

export const zGetPetByIdPath = z.object({
    petId: z.string().min(1),
})

/** The requested pet. */
export const zGetPetByIdResponse = zPet

export const zUpdatePetBody = zUpdatePet

export const zUpdatePetPath = z.object({
    petId: z.string().min(1),
})

/** The updated pet. */
export const zUpdatePetResponse = zPet
