// This file is auto-generated by @hey-api/openapi-ts

import type {
    CreatePetData,
    CreatePetError,
    CreatePetResponse,
    DeletePetData,
    DeletePetError,
    DeletePetResponse,
    FindPetsByStatusData,
    FindPetsByStatusError,
    FindPetsByStatusResponse,
    GetPetByIdData,
    GetPetByIdError,
    GetPetByIdResponse,
    UpdatePetData,
    UpdatePetError,
    UpdatePetResponse,
} from '../types.gen'

import {
    type InfiniteData,
    infiniteQueryOptions,
    queryOptions,
    type UseMutationOptions,
} from '@tanstack/react-query'

import { client } from '../client.gen'
import {
    createPet,
    deletePet,
    findPetsByStatus,
    getPetById,
    type Options,
    updatePet,
} from '../sdk.gen'

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string
        _infinite?: boolean
        tags?: ReadonlyArray<string>
    },
]

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
    } as QueryKey<TOptions>[0]
    if (infinite) {
        params._infinite = infinite
    }
    if (tags) {
        params.tags = tags
    }
    if (options?.body) {
        params.body = options.body
    }
    if (options?.headers) {
        params.headers = options.headers
    }
    if (options?.path) {
        params.path = options.path
    }
    if (options?.query) {
        params.query = options.query
    }
    return [params]
}

export const findPetsByStatusQueryKey = (options?: Options<FindPetsByStatusData>) =>
    createQueryKey('findPetsByStatus', options, false, ['pets'])

/**
 * Find pets by status
 *
 * Returns one offset-based page of pets, optionally filtered by status.
 */
export const findPetsByStatusOptions = (options?: Options<FindPetsByStatusData>) =>
    queryOptions<
        FindPetsByStatusResponse,
        FindPetsByStatusError,
        FindPetsByStatusResponse,
        ReturnType<typeof findPetsByStatusQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await findPetsByStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: findPetsByStatusQueryKey(options),
    })

const createInfiniteParams = <
    K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
    queryKey: QueryKey<Options>,
    page: K,
) => {
    const params = { ...queryKey[0] }
    if (page.body) {
        params.body = {
            ...(queryKey[0].body as any),
            ...(page.body as any),
        }
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers,
        }
    }
    if (page.path) {
        params.path = {
            ...(queryKey[0].path as any),
            ...(page.path as any),
        }
    }
    if (page.query) {
        params.query = {
            ...(queryKey[0].query as any),
            ...(page.query as any),
        }
    }
    return params as unknown as typeof page
}

export const findPetsByStatusInfiniteQueryKey = (
    options?: Options<FindPetsByStatusData>,
): QueryKey<Options<FindPetsByStatusData>> =>
    createQueryKey('findPetsByStatus', options, true, ['pets'])

/**
 * Find pets by status
 *
 * Returns one offset-based page of pets, optionally filtered by status.
 */
export const findPetsByStatusInfiniteOptions = (options?: Options<FindPetsByStatusData>) => {
    const opts = infiniteQueryOptions<
        FindPetsByStatusResponse,
        FindPetsByStatusError,
        InfiniteData<FindPetsByStatusResponse>,
        QueryKey<Options<FindPetsByStatusData>>,
        | number
        | Pick<QueryKey<Options<FindPetsByStatusData>>[0], 'body' | 'headers' | 'path' | 'query'>
    >(
        // @ts-ignore
        {
            queryFn: async ({ pageParam, queryKey, signal }) => {
                // @ts-ignore
                const page: Pick<
                    QueryKey<Options<FindPetsByStatusData>>[0],
                    'body' | 'headers' | 'path' | 'query'
                > =
                    typeof pageParam === 'object'
                        ? pageParam
                        : {
                              query: {
                                  offset: pageParam,
                              },
                          }
                const params = createInfiniteParams(queryKey, page)
                const { data } = await findPetsByStatus({
                    ...options,
                    ...params,
                    signal,
                    throwOnError: true,
                })
                return data
            },
            queryKey: findPetsByStatusInfiniteQueryKey(options),
        },
    )
    return opts as Omit<typeof opts, 'initialData'>
}

export type MutationKey<TOptions extends Partial<Options>> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string
        tags?: ReadonlyArray<string>
    },
]

const createMutationKey = <TOptions extends Partial<Options>>(
    id: string,
    options?: TOptions,
    tags?: ReadonlyArray<string>,
): [MutationKey<TOptions>[0]] => {
    const params: MutationKey<TOptions>[0] = {
        _id: id,
        baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
    }
    if (tags) {
        params.tags = tags
    }
    if (options?.body) {
        params.body = options.body
    }
    if (options?.headers) {
        params.headers = options.headers
    }
    if (options?.path) {
        params.path = options.path
    }
    if (options?.query) {
        params.query = options.query
    }
    return [params]
}

export const createPetMutationKey = (options?: Partial<Options<CreatePetData>>) =>
    createMutationKey('createPet', options, ['pets'])

/**
 * Create a pet
 *
 * Adds one pet to the example catalog.
 */
export const createPetMutation = (
    options?: Partial<Options<CreatePetData>>,
): UseMutationOptions<CreatePetResponse, CreatePetError, Options<CreatePetData>> => {
    const mutationOptions: UseMutationOptions<
        CreatePetResponse,
        CreatePetError,
        Options<CreatePetData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPet({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
        mutationKey: createPetMutationKey(options),
    }
    return mutationOptions
}

export const deletePetMutationKey = (options?: Partial<Options<DeletePetData>>) =>
    createMutationKey('deletePet', options, ['pets'])

/**
 * Delete a pet
 *
 * Removes one pet from the example catalog.
 */
export const deletePetMutation = (
    options?: Partial<Options<DeletePetData>>,
): UseMutationOptions<DeletePetResponse, DeletePetError, Options<DeletePetData>> => {
    const mutationOptions: UseMutationOptions<
        DeletePetResponse,
        DeletePetError,
        Options<DeletePetData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePet({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
        mutationKey: deletePetMutationKey(options),
    }
    return mutationOptions
}

export const getPetByIdQueryKey = (options: Options<GetPetByIdData>) =>
    createQueryKey('getPetById', options, false, ['pets'])

/**
 * Get a pet
 *
 * Returns one pet by its stable identifier.
 */
export const getPetByIdOptions = (options: Options<GetPetByIdData>) =>
    queryOptions<
        GetPetByIdResponse,
        GetPetByIdError,
        GetPetByIdResponse,
        ReturnType<typeof getPetByIdQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPetById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getPetByIdQueryKey(options),
    })

export const updatePetMutationKey = (options?: Partial<Options<UpdatePetData>>) =>
    createMutationKey('updatePet', options, ['pets'])

/**
 * Update a pet
 *
 * Partially updates the name or status of one pet.
 */
export const updatePetMutation = (
    options?: Partial<Options<UpdatePetData>>,
): UseMutationOptions<UpdatePetResponse, UpdatePetError, Options<UpdatePetData>> => {
    const mutationOptions: UseMutationOptions<
        UpdatePetResponse,
        UpdatePetError,
        Options<UpdatePetData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePet({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
        mutationKey: updatePetMutationKey(options),
    }
    return mutationOptions
}
