/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    UpdatePet200,
    UpdatePet404,
    UpdatePet422,
    UpdatePetMutationRequest,
    UpdatePetMutationResponse,
    UpdatePetPathParams,
} from '../../models/petsController/UpdatePet'

import { faker } from '@faker-js/faker'

import { createPet } from '../createPet'
import { createProblem } from '../createProblem'
import { createUpdatePet } from '../createUpdatePet'

export function createUpdatePetPathParams(
    data?: Partial<UpdatePetPathParams>,
): UpdatePetPathParams {
    faker.seed([100])
    return {
        ...{ petId: faker.string.alpha({ length: 1 }) },
        ...(data || {}),
    }
}

/** The updated pet. */
export function createUpdatePet200(data?: Partial<UpdatePet200>): UpdatePet200 {
    faker.seed([100])
    return createPet(data)
}

/** The requested pet does not exist. */
export function createUpdatePet404(data?: Partial<UpdatePet404>): UpdatePet404 {
    faker.seed([100])
    return createProblem(data)
}

/** The request does not satisfy the contract. */
export function createUpdatePet422(data?: Partial<UpdatePet422>): UpdatePet422 {
    faker.seed([100])
    return createProblem(data)
}

export function createUpdatePetMutationRequest(
    data?: Partial<UpdatePetMutationRequest>,
): UpdatePetMutationRequest {
    faker.seed([100])
    return createUpdatePet(data)
}

export function createUpdatePetMutationResponse(
    data?: Partial<UpdatePetMutationResponse>,
): UpdatePetMutationResponse {
    faker.seed([100])
    return data || faker.helpers.arrayElement<any>([createUpdatePet200()])
}
