/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    CreatePet201,
    CreatePet422,
    CreatePetMutationRequest,
    CreatePetMutationResponse,
} from '../../models/petsController/CreatePet'

import { faker } from '@faker-js/faker'

import { createCreatePet } from '../createCreatePet'
import { createPet } from '../createPet'
import { createProblem } from '../createProblem'

/** The created pet. */
export function createCreatePet201(data?: Partial<CreatePet201>): CreatePet201 {
    faker.seed([100])
    return createPet(data)
}

/** The request does not satisfy the contract. */
export function createCreatePet422(data?: Partial<CreatePet422>): CreatePet422 {
    faker.seed([100])
    return createProblem(data)
}

export function createCreatePetMutationRequest(
    data?: Partial<CreatePetMutationRequest>,
): CreatePetMutationRequest {
    faker.seed([100])
    return createCreatePet(data)
}

export function createCreatePetMutationResponse(
    data?: Partial<CreatePetMutationResponse>,
): CreatePetMutationResponse {
    faker.seed([100])
    return data || faker.helpers.arrayElement<any>([createCreatePet201()])
}
