/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    GetPetById200,
    GetPetById404,
    GetPetByIdPathParams,
    GetPetByIdQueryResponse,
} from '../../models/petsController/GetPetById'

import { faker } from '@faker-js/faker'

import { createPet } from '../createPet'
import { createProblem } from '../createProblem'

export function createGetPetByIdPathParams(
    data?: Partial<GetPetByIdPathParams>,
): GetPetByIdPathParams {
    faker.seed([100])
    return {
        ...{ petId: faker.string.alpha({ length: 1 }) },
        ...(data || {}),
    }
}

/** The requested pet. */
export function createGetPetById200(data?: Partial<GetPetById200>): GetPetById200 {
    faker.seed([100])
    return createPet(data)
}

/** The requested pet does not exist. */
export function createGetPetById404(data?: Partial<GetPetById404>): GetPetById404 {
    faker.seed([100])
    return createProblem(data)
}

export function createGetPetByIdQueryResponse(
    data?: Partial<GetPetByIdQueryResponse>,
): GetPetByIdQueryResponse {
    faker.seed([100])
    return data || faker.helpers.arrayElement<any>([createGetPetById200()])
}
