/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    FindPetsByStatus200,
    FindPetsByStatus422,
    FindPetsByStatusQueryParams,
    FindPetsByStatusQueryResponse,
} from '../../models/petsController/FindPetsByStatus'

import { faker } from '@faker-js/faker'

import { createPetPage } from '../createPetPage'
import { createPetStatus } from '../createPetStatus'
import { createProblem } from '../createProblem'

export function createFindPetsByStatusQueryParams(
    data?: Partial<FindPetsByStatusQueryParams>,
): FindPetsByStatusQueryParams {
    faker.seed([100])
    return {
        ...{
            get status() {
                return faker.helpers.multiple(() => createPetStatus())
            },
            offset: faker.number.int({ min: 0 }),
            limit: faker.number.int({ min: 1, max: 100 }),
            ...(data || {}),
        },
    }
}

/** One page of pets. */
export function createFindPetsByStatus200(
    data?: Partial<FindPetsByStatus200>,
): FindPetsByStatus200 {
    faker.seed([100])
    return createPetPage(data)
}

/** The request does not satisfy the contract. */
export function createFindPetsByStatus422(
    data?: Partial<FindPetsByStatus422>,
): FindPetsByStatus422 {
    faker.seed([100])
    return createProblem(data)
}

export function createFindPetsByStatusQueryResponse(
    data?: Partial<FindPetsByStatusQueryResponse>,
): FindPetsByStatusQueryResponse {
    faker.seed([100])
    return data || faker.helpers.arrayElement<any>([createFindPetsByStatus200()])
}
