/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    DeletePet404,
    DeletePetMutationResponse,
    DeletePetPathParams,
} from '../../models/petsController/DeletePet'

import { faker } from '@faker-js/faker'

import { createProblem } from '../createProblem'

export function createDeletePetPathParams(
    data?: Partial<DeletePetPathParams>,
): DeletePetPathParams {
    faker.seed([100])
    return {
        ...{ petId: faker.string.alpha({ length: 1 }) },
        ...(data || {}),
    }
}

/** The pet was deleted. */
export function createDeletePet204() {
    faker.seed([100])
    return undefined
}

/** The requested pet does not exist. */
export function createDeletePet404(data?: Partial<DeletePet404>): DeletePet404 {
    faker.seed([100])
    return createProblem(data)
}

export function createDeletePetMutationResponse(
    data?: Partial<DeletePetMutationResponse>,
): DeletePetMutationResponse {
    faker.seed([100])
    return data || faker.helpers.arrayElement<any>([createDeletePet204()])
}
