import type { PluginFactoryOptions } from '@kubb/core'

import path from 'node:path'

import { definePlugin } from '@kubb/core'
import { pluginFakerName } from '@kubb/plugin-faker'
import { OperationGenerator, pluginOasName } from '@kubb/plugin-oas'

export const pluginMockClientRoutesName = 'plugin-mock-client-routes'

type OpenApiMethod = 'delete' | 'get' | 'patch' | 'post' | 'put'
type GeneratedBaseName = `${string}.${string}`

interface OperationLike {
    getOperationId: (options: { friendlyCase: boolean }) => string
    schema?: {
        responses?: Record<string, unknown>
        tags?: string[]
    }
}

interface Options {
    output?: {
        path: string
    }
    mocksImportPath?: string
    mockClientImportPath?: string
}

interface ResolvedOptions {
    output: {
        path: string
    }
    mocksImportPath: string
    mockClientImportPath: string
}

type PluginMockClientRoutes = PluginFactoryOptions<
    typeof pluginMockClientRoutesName,
    Options,
    ResolvedOptions
>

export interface MockClientRouteDefinition {
    method: OpenApiMethod
    path: string
    operationId: string
    status: number
    tag?: string
}

interface RenderOptions {
    mocksImportPath: string
    mockClientImportPath: string
}

const successfulStatusPattern = /^[23]\d\d$/
const exactSuccessfulStatusPattern = /^2\d\d$/
const pathParameterPattern = /\{[^}]+\}/g

function splitWords(value: string) {
    return value.match(/[A-Z]?[a-z]+|[A-Z]+(?![a-z])|\d+/g) ?? []
}

function capitalize(value: string) {
    return value.charAt(0).toUpperCase() + value.slice(1).toLowerCase()
}

function toPascalCase(value: string) {
    return splitWords(value).map(capitalize).join('')
}

function toCamelCase(value: string) {
    const [firstWord, ...restWords] = splitWords(value)

    if (firstWord === undefined) {
        return ''
    }

    return [firstWord.toLowerCase(), ...restWords.map(capitalize)].join('')
}

function toMockGroupName(tag?: string) {
    if (tag === undefined || tag === '') {
        return undefined
    }

    return `${toCamelCase(tag)}Service`
}

function escapeRegexLiteral(value: string) {
    return value.replaceAll(/[\\^$.*+?()[\]{}|/]/g, '\\$&')
}

function toRoutePattern(pathname: string) {
    let offset = 0
    let source = ''

    for (const match of pathname.matchAll(pathParameterPattern)) {
        const [value] = match
        const index = match.index

        source += escapeRegexLiteral(pathname.slice(offset, index))
        source += '[^/]+'
        offset = index + value.length
    }

    source += escapeRegexLiteral(pathname.slice(offset))

    return `^${source}$`
}

function toMockFactoryName(route: MockClientRouteDefinition) {
    const suffix = route.method === 'get' ? 'QueryResponse' : 'MutationResponse'

    return `create${toPascalCase(route.operationId)}${suffix}`
}

function toMockFileName(route: MockClientRouteDefinition) {
    return `create${toPascalCase(route.operationId)}`
}

function toMockImportPath(route: MockClientRouteDefinition, mocksImportPath: string) {
    const groupName = toMockGroupName(route.tag)
    const fileName = toMockFileName(route)

    return [mocksImportPath, groupName, fileName]
        .filter((item): item is string => item !== undefined && item !== '')
        .join('/')
}

function compareRoutes(a: MockClientRouteDefinition, b: MockClientRouteDefinition) {
    const aParamsCount = a.path.match(pathParameterPattern)?.length ?? 0
    const bParamsCount = b.path.match(pathParameterPattern)?.length ?? 0

    return aParamsCount - bParamsCount || b.path.length - a.path.length
}

function renderImports(routes: MockClientRouteDefinition[], mocksImportPath: string) {
    return routes
        .map((route) => ({
            name: toMockFactoryName(route),
            path: toMockImportPath(route, mocksImportPath),
        }))
        .map(({ name, path: importPath }) => `import { ${name} } from '${importPath}'`)
        .join('\n')
}

function renderRoute(route: MockClientRouteDefinition) {
    const status = route.status === 200 ? '' : `, status: ${route.status}`

    return `{ method: '${route.method.toUpperCase()}', pattern: /${toRoutePattern(route.path)}/${status}, create: ${toMockFactoryName(route)} }`
}

export function renderMockClientRoutes(
    routes: MockClientRouteDefinition[],
    { mocksImportPath, mockClientImportPath }: RenderOptions,
) {
    const orderedRoutes = [...routes].sort(compareRoutes)

    return `/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { MockRoute } from '${mockClientImportPath}'
${renderImports(orderedRoutes, mocksImportPath)}

export const mockRoutes = [
${orderedRoutes.map((route) => `\t${renderRoute(route)},`).join('\n')}
] satisfies MockRoute[]
`
}

function getPreferredMockStatus(statusCodes: string[]) {
    const status =
        statusCodes.find((item) => item.match(exactSuccessfulStatusPattern)) ??
        statusCodes.find((item) => item.match(successfulStatusPattern))

    return status === undefined ? 200 : Number(status)
}

function getOperationTag(operation: OperationLike) {
    return operation.schema?.tags?.at(0)
}

function getOperationStatusCodes(operation: OperationLike) {
    return Object.keys(operation.schema?.responses ?? {})
}

function isOpenApiMethod(method: string): method is OpenApiMethod {
    return ['delete', 'get', 'patch', 'post', 'put'].includes(method)
}

export const pluginMockClientRoutes = definePlugin<PluginMockClientRoutes>((options) => {
    const {
        output = { path: 'mock-client-routes.ts' },
        mocksImportPath = './mocks',
        mockClientImportPath = '../mock-client',
    } = options

    return {
        name: pluginMockClientRoutesName,
        options: {
            output,
            mocksImportPath,
            mockClientImportPath,
        },
        pre: [pluginOasName, pluginFakerName],
        async install() {
            const oas = await this.getOas()
            const generator = new OperationGenerator<PluginMockClientRoutes>(this.plugin.options, {
                fabric: this.fabric,
                oas,
                pluginManager: this.pluginManager,
                plugin: this.plugin,
                contentType: undefined,
                exclude: undefined,
                include: undefined,
                override: undefined,
                mode: 'split',
            })
            const operations = await generator.getOperations()
            const routes = operations.flatMap<MockClientRouteDefinition>(
                ({ method, operation, path: operationPath }) => {
                    if (!isOpenApiMethod(method)) {
                        return []
                    }

                    return [
                        {
                            method,
                            path: operationPath,
                            operationId: operation.getOperationId({ friendlyCase: true }),
                            status: getPreferredMockStatus(getOperationStatusCodes(operation)),
                            tag: getOperationTag(operation),
                        },
                    ]
                },
            )

            await this.upsertFile({
                path: path.resolve(this.config.root, this.config.output.path, output.path),
                baseName: path.basename(output.path) as GeneratedBaseName,
                sources: [
                    {
                        name: 'mockRoutes',
                        value: renderMockClientRoutes(routes, {
                            mocksImportPath,
                            mockClientImportPath,
                        }),
                        isExportable: true,
                        isIndexable: false,
                    },
                ],
                imports: [],
                exports: [],
                meta: {
                    pluginKey: this.plugin.key,
                },
            })
        },
    }
})
