/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    CreatePetMutationRequest,
    CreatePetMutationResponse,
    CreatePet422,
} from '../../models/petsController/CreatePet'

import { mutationOptions, useMutation } from '@tanstack/react-query'

import { createPet } from '../../clients/petsController/createPet'

export const createPetMutationKey = () => [{ url: '/pets' }] as const

export type CreatePetMutationKey = ReturnType<typeof createPetMutationKey>

export function createPetMutationOptions<TContext = unknown>(
    config: Partial<RequestConfig<CreatePetMutationRequest>> & { client?: Client } = {},
) {
    const mutationKey = createPetMutationKey()
    return mutationOptions<
        CreatePetMutationResponse,
        ResponseErrorConfig<CreatePet422>,
        { data: CreatePetMutationRequest },
        TContext
    >({
        mutationKey,
        mutationFn: async ({ data }) => {
            return createPet({ data }, config)
        },
    })
}

/**
 * Adds one pet to the example catalog.
 *
 * @summary Create a pet
 * {@link /pets}
 */
export function useCreatePet<TContext>(
    options: {
        mutation?: UseMutationOptions<
            CreatePetMutationResponse,
            ResponseErrorConfig<CreatePet422>,
            { data: CreatePetMutationRequest },
            TContext
        > & { client?: QueryClient }
        client?: Partial<RequestConfig<CreatePetMutationRequest>> & { client?: Client }
    } = {},
) {
    const { mutation = {}, client: config = {} } = options ?? {}
    const { client: queryClient, ...mutationOptions } = mutation
    const mutationKey = mutationOptions.mutationKey ?? createPetMutationKey()

    const baseOptions = createPetMutationOptions(config) as UseMutationOptions<
        CreatePetMutationResponse,
        ResponseErrorConfig<CreatePet422>,
        { data: CreatePetMutationRequest },
        TContext
    >

    return useMutation<
        CreatePetMutationResponse,
        ResponseErrorConfig<CreatePet422>,
        { data: CreatePetMutationRequest },
        TContext
    >(
        {
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
        },
        queryClient,
    ) as UseMutationResult<
        CreatePetMutationResponse,
        ResponseErrorConfig<CreatePet422>,
        { data: CreatePetMutationRequest },
        TContext
    >
}
