/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    DeletePetMutationResponse,
    DeletePetPathParams,
    DeletePet404,
} from '../../models/petsController/DeletePet'

import { mutationOptions, useMutation } from '@tanstack/react-query'

import { deletePet } from '../../clients/petsController/deletePet'

export const deletePetMutationKey = () => [{ url: '/pets/:petId' }] as const

export type DeletePetMutationKey = ReturnType<typeof deletePetMutationKey>

export function deletePetMutationOptions<TContext = unknown>(
    config: Partial<RequestConfig> & { client?: Client } = {},
) {
    const mutationKey = deletePetMutationKey()
    return mutationOptions<
        DeletePetMutationResponse,
        ResponseErrorConfig<DeletePet404>,
        { petId: DeletePetPathParams['petId'] },
        TContext
    >({
        mutationKey,
        mutationFn: async ({ petId }) => {
            return deletePet({ petId }, config)
        },
    })
}

/**
 * Removes one pet from the example catalog.
 *
 * @summary Delete a pet
 * {@link /pets/:petId}
 */
export function useDeletePet<TContext>(
    options: {
        mutation?: UseMutationOptions<
            DeletePetMutationResponse,
            ResponseErrorConfig<DeletePet404>,
            { petId: DeletePetPathParams['petId'] },
            TContext
        > & { client?: QueryClient }
        client?: Partial<RequestConfig> & { client?: Client }
    } = {},
) {
    const { mutation = {}, client: config = {} } = options ?? {}
    const { client: queryClient, ...mutationOptions } = mutation
    const mutationKey = mutationOptions.mutationKey ?? deletePetMutationKey()

    const baseOptions = deletePetMutationOptions(config) as UseMutationOptions<
        DeletePetMutationResponse,
        ResponseErrorConfig<DeletePet404>,
        { petId: DeletePetPathParams['petId'] },
        TContext
    >

    return useMutation<
        DeletePetMutationResponse,
        ResponseErrorConfig<DeletePet404>,
        { petId: DeletePetPathParams['petId'] },
        TContext
    >(
        {
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
        },
        queryClient,
    ) as UseMutationResult<
        DeletePetMutationResponse,
        ResponseErrorConfig<DeletePet404>,
        { petId: DeletePetPathParams['petId'] },
        TContext
    >
}
