/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    QueryKey,
    QueryClient,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    FindPetsByStatusQueryResponse,
    FindPetsByStatusQueryParams,
    FindPetsByStatus422,
} from '../../models/petsController/FindPetsByStatus'

import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

import { findPetsByStatus } from '../../clients/petsController/findPetsByStatus'

export const findPetsByStatusSuspenseQueryKey = (params?: FindPetsByStatusQueryParams) =>
    [{ url: '/pets' }, ...(params ? [params] : [])] as const

export type FindPetsByStatusSuspenseQueryKey = ReturnType<typeof findPetsByStatusSuspenseQueryKey>

export function findPetsByStatusSuspenseQueryOptions(
    { params }: { params?: FindPetsByStatusQueryParams } = {},
    config: Partial<RequestConfig> & { client?: Client } = {},
) {
    const queryKey = findPetsByStatusSuspenseQueryKey(params)
    return queryOptions<
        FindPetsByStatusQueryResponse,
        ResponseErrorConfig<FindPetsByStatus422>,
        FindPetsByStatusQueryResponse,
        typeof queryKey
    >({
        queryKey,
        queryFn: async ({ signal }) => {
            return findPetsByStatus(
                { params: params },
                { ...config, signal: config.signal ?? signal },
            )
        },
    })
}

/**
 * Returns one offset-based page of pets, optionally filtered by status.
 *
 * @summary Find pets by status
 * {@link /pets}
 */
export function useFindPetsByStatusSuspense<
    TData = FindPetsByStatusQueryResponse,
    TQueryKey extends QueryKey = FindPetsByStatusSuspenseQueryKey,
>(
    { params }: { params?: FindPetsByStatusQueryParams } = {},
    options: {
        query?: Partial<
            UseSuspenseQueryOptions<
                FindPetsByStatusQueryResponse,
                ResponseErrorConfig<FindPetsByStatus422>,
                TData,
                TQueryKey
            >
        > & { client?: QueryClient }
        client?: Partial<RequestConfig> & { client?: Client }
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {}
    const { client: queryClient, ...resolvedOptions } = queryConfig
    const queryKey = resolvedOptions?.queryKey ?? findPetsByStatusSuspenseQueryKey(params)

    const query = useSuspenseQuery(
        {
            ...findPetsByStatusSuspenseQueryOptions({ params }, config),
            ...resolvedOptions,
            queryKey,
        } as unknown as UseSuspenseQueryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<FindPetsByStatus422>> & {
        queryKey: TQueryKey
    }

    query.queryKey = queryKey as TQueryKey

    return query
}
