/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    QueryKey,
    QueryClient,
    QueryObserverOptions,
    UseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    FindPetsByStatusQueryResponse,
    FindPetsByStatusQueryParams,
    FindPetsByStatus422,
} from '../../models/petsController/FindPetsByStatus'

import { queryOptions, useQuery } from '@tanstack/react-query'

import { findPetsByStatus } from '../../clients/petsController/findPetsByStatus'

export const findPetsByStatusQueryKey = (params?: FindPetsByStatusQueryParams) =>
    [{ url: '/pets' }, ...(params ? [params] : [])] as const

export type FindPetsByStatusQueryKey = ReturnType<typeof findPetsByStatusQueryKey>

export function findPetsByStatusQueryOptions(
    { params }: { params?: FindPetsByStatusQueryParams } = {},
    config: Partial<RequestConfig> & { client?: Client } = {},
) {
    const queryKey = findPetsByStatusQueryKey(params)
    return queryOptions<
        FindPetsByStatusQueryResponse,
        ResponseErrorConfig<FindPetsByStatus422>,
        FindPetsByStatusQueryResponse,
        typeof queryKey
    >({
        queryKey,
        queryFn: async ({ signal }) => {
            return findPetsByStatus(
                { params: params },
                { ...config, signal: config.signal ?? signal },
            )
        },
    })
}

/**
 * Returns one offset-based page of pets, optionally filtered by status.
 *
 * @summary Find pets by status
 * {@link /pets}
 */
export function useFindPetsByStatus<
    TData = FindPetsByStatusQueryResponse,
    TQueryData = FindPetsByStatusQueryResponse,
    TQueryKey extends QueryKey = FindPetsByStatusQueryKey,
>(
    { params }: { params?: FindPetsByStatusQueryParams } = {},
    options: {
        query?: Partial<
            QueryObserverOptions<
                FindPetsByStatusQueryResponse,
                ResponseErrorConfig<FindPetsByStatus422>,
                TData,
                TQueryData,
                TQueryKey
            >
        > & { client?: QueryClient }
        client?: Partial<RequestConfig> & { client?: Client }
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {}
    const { client: queryClient, ...resolvedOptions } = queryConfig
    const queryKey = resolvedOptions?.queryKey ?? findPetsByStatusQueryKey(params)

    const query = useQuery(
        {
            ...findPetsByStatusQueryOptions({ params }, config),
            ...resolvedOptions,
            queryKey,
        } as unknown as QueryObserverOptions,
        queryClient,
    ) as UseQueryResult<TData, ResponseErrorConfig<FindPetsByStatus422>> & { queryKey: TQueryKey }

    query.queryKey = queryKey as TQueryKey

    return query
}
