/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    InfiniteData,
    QueryKey,
    QueryClient,
    InfiniteQueryObserverOptions,
    UseInfiniteQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    FindPetsByStatusQueryResponse,
    FindPetsByStatusQueryParams,
    FindPetsByStatus422,
} from '../../models/petsController/FindPetsByStatus'

import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

import { findPetsByStatus } from '../../clients/petsController/findPetsByStatus'

export const findPetsByStatusInfiniteQueryKey = (params?: FindPetsByStatusQueryParams) =>
    [{ url: '/pets' }, ...(params ? [params] : [])] as const

export type FindPetsByStatusInfiniteQueryKey = ReturnType<typeof findPetsByStatusInfiniteQueryKey>

export function findPetsByStatusInfiniteQueryOptions(
    { params }: { params?: FindPetsByStatusQueryParams } = {},
    config: Partial<RequestConfig> & { client?: Client } = {},
) {
    const queryKey = findPetsByStatusInfiniteQueryKey(params)
    return infiniteQueryOptions<
        FindPetsByStatusQueryResponse,
        ResponseErrorConfig<FindPetsByStatus422>,
        InfiniteData<FindPetsByStatusQueryResponse>,
        typeof queryKey,
        NonNullable<FindPetsByStatusQueryParams['offset']>
    >({
        queryKey,
        queryFn: async ({ signal, pageParam }) => {
            params = {
                ...(params ?? {}),
                ['offset']: pageParam as unknown as FindPetsByStatusQueryParams['offset'],
            } as FindPetsByStatusQueryParams
            return findPetsByStatus(
                { params: params },
                { ...config, signal: config.signal ?? signal },
            )
        },
        initialPageParam: 0,
        getNextPageParam: (lastPage, _allPages, lastPageParam) =>
            Array.isArray(lastPage) && lastPage.length === 0 ? undefined : lastPageParam + 1,
        getPreviousPageParam: (_firstPage, _allPages, firstPageParam) =>
            firstPageParam <= 1 ? undefined : firstPageParam - 1,
    })
}

/**
 * Returns one offset-based page of pets, optionally filtered by status.
 *
 * @summary Find pets by status
 * {@link /pets}
 */
export function useFindPetsByStatusInfinite<
    TQueryFnData = FindPetsByStatusQueryResponse,
    TError = ResponseErrorConfig<FindPetsByStatus422>,
    TData = InfiniteData<TQueryFnData>,
    TQueryKey extends QueryKey = FindPetsByStatusInfiniteQueryKey,
    TPageParam = NonNullable<FindPetsByStatusQueryParams['offset']>,
>(
    { params }: { params?: FindPetsByStatusQueryParams } = {},
    options: {
        query?: Partial<
            InfiniteQueryObserverOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>
        > & { client?: QueryClient }
        client?: Partial<RequestConfig> & { client?: Client }
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {}
    const { client: queryClient, ...resolvedOptions } = queryConfig
    const queryKey = resolvedOptions?.queryKey ?? findPetsByStatusInfiniteQueryKey(params)

    const query = useInfiniteQuery(
        {
            ...findPetsByStatusInfiniteQueryOptions({ params }, config),
            ...resolvedOptions,
            queryKey,
        } as unknown as InfiniteQueryObserverOptions<
            TQueryFnData,
            TError,
            TData,
            TQueryKey,
            TPageParam
        >,
        queryClient,
    ) as UseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey }

    query.queryKey = queryKey as TQueryKey

    return query
}
