/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    QueryKey,
    QueryClient,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    GetPetByIdQueryResponse,
    GetPetByIdPathParams,
    GetPetById404,
} from '../../models/petsController/GetPetById'

import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

import { getPetById } from '../../clients/petsController/getPetById'

export const getPetByIdSuspenseQueryKey = ({
    petId,
}: {
    petId: GetPetByIdPathParams['petId'] | undefined
}) => [{ url: '/pets/:petId', params: { petId: petId } }] as const

export type GetPetByIdSuspenseQueryKey = ReturnType<typeof getPetByIdSuspenseQueryKey>

export function getPetByIdSuspenseQueryOptions(
    { petId }: { petId: GetPetByIdPathParams['petId'] },
    config: Partial<RequestConfig> & { client?: Client } = {},
) {
    const queryKey = getPetByIdSuspenseQueryKey({ petId })
    return queryOptions<
        GetPetByIdQueryResponse,
        ResponseErrorConfig<GetPetById404>,
        GetPetByIdQueryResponse,
        typeof queryKey
    >({
        queryKey,
        queryFn: async ({ signal }) => {
            return getPetById({ petId: petId }, { ...config, signal: config.signal ?? signal })
        },
    })
}

/**
 * Returns one pet by its stable identifier.
 *
 * @summary Get a pet
 * {@link /pets/:petId}
 */
export function useGetPetByIdSuspense<
    TData = GetPetByIdQueryResponse,
    TQueryKey extends QueryKey = GetPetByIdSuspenseQueryKey,
>(
    { petId }: { petId: GetPetByIdPathParams['petId'] },
    options: {
        query?: Partial<
            UseSuspenseQueryOptions<
                GetPetByIdQueryResponse,
                ResponseErrorConfig<GetPetById404>,
                TData,
                TQueryKey
            >
        > & { client?: QueryClient }
        client?: Partial<RequestConfig> & { client?: Client }
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {}
    const { client: queryClient, ...resolvedOptions } = queryConfig
    const queryKey = resolvedOptions?.queryKey ?? getPetByIdSuspenseQueryKey({ petId })

    const query = useSuspenseQuery(
        {
            ...getPetByIdSuspenseQueryOptions({ petId }, config),
            ...resolvedOptions,
            queryKey,
        } as unknown as UseSuspenseQueryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetPetById404>> & { queryKey: TQueryKey }

    query.queryKey = queryKey as TQueryKey

    return query
}
