/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
    QueryKey,
    QueryClient,
    QueryObserverOptions,
    UseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    GetPetByIdQueryResponse,
    GetPetByIdPathParams,
    GetPetById404,
} from '../../models/petsController/GetPetById'

import { queryOptions, useQuery } from '@tanstack/react-query'

import { getPetById } from '../../clients/petsController/getPetById'

export const getPetByIdQueryKey = ({
    petId,
}: {
    petId: GetPetByIdPathParams['petId'] | undefined
}) => [{ url: '/pets/:petId', params: { petId: petId } }] as const

export type GetPetByIdQueryKey = ReturnType<typeof getPetByIdQueryKey>

export function getPetByIdQueryOptions(
    { petId }: { petId: GetPetByIdPathParams['petId'] | undefined },
    config: Partial<RequestConfig> & { client?: Client } = {},
) {
    const queryKey = getPetByIdQueryKey({ petId })
    return queryOptions<
        GetPetByIdQueryResponse,
        ResponseErrorConfig<GetPetById404>,
        GetPetByIdQueryResponse,
        typeof queryKey
    >({
        enabled: !!petId,
        queryKey,
        queryFn: async ({ signal }) => {
            return getPetById({ petId: petId! }, { ...config, signal: config.signal ?? signal })
        },
    })
}

/**
 * Returns one pet by its stable identifier.
 *
 * @summary Get a pet
 * {@link /pets/:petId}
 */
export function useGetPetById<
    TData = GetPetByIdQueryResponse,
    TQueryData = GetPetByIdQueryResponse,
    TQueryKey extends QueryKey = GetPetByIdQueryKey,
>(
    { petId }: { petId: GetPetByIdPathParams['petId'] | undefined },
    options: {
        query?: Partial<
            QueryObserverOptions<
                GetPetByIdQueryResponse,
                ResponseErrorConfig<GetPetById404>,
                TData,
                TQueryData,
                TQueryKey
            >
        > & { client?: QueryClient }
        client?: Partial<RequestConfig> & { client?: Client }
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {}
    const { client: queryClient, ...resolvedOptions } = queryConfig
    const queryKey = resolvedOptions?.queryKey ?? getPetByIdQueryKey({ petId })

    const query = useQuery(
        {
            ...getPetByIdQueryOptions({ petId }, config),
            ...resolvedOptions,
            queryKey,
        } as unknown as QueryObserverOptions,
        queryClient,
    ) as UseQueryResult<TData, ResponseErrorConfig<GetPetById404>> & { queryKey: TQueryKey }

    query.queryKey = queryKey as TQueryKey

    return query
}
