/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    UpdatePetMutationRequest,
    UpdatePetMutationResponse,
    UpdatePetPathParams,
    UpdatePet404,
    UpdatePet422,
} from '../../models/petsController/UpdatePet'

import { mutationOptions, useMutation } from '@tanstack/react-query'

import { updatePet } from '../../clients/petsController/updatePet'

export const updatePetMutationKey = () => [{ url: '/pets/:petId' }] as const

export type UpdatePetMutationKey = ReturnType<typeof updatePetMutationKey>

export function updatePetMutationOptions<TContext = unknown>(
    config: Partial<RequestConfig<UpdatePetMutationRequest>> & { client?: Client } = {},
) {
    const mutationKey = updatePetMutationKey()
    return mutationOptions<
        UpdatePetMutationResponse,
        ResponseErrorConfig<UpdatePet404 | UpdatePet422>,
        { petId: UpdatePetPathParams['petId']; data: UpdatePetMutationRequest },
        TContext
    >({
        mutationKey,
        mutationFn: async ({ petId, data }) => {
            return updatePet({ petId, data }, config)
        },
    })
}

/**
 * Partially updates the name or status of one pet.
 *
 * @summary Update a pet
 * {@link /pets/:petId}
 */
export function useUpdatePet<TContext>(
    options: {
        mutation?: UseMutationOptions<
            UpdatePetMutationResponse,
            ResponseErrorConfig<UpdatePet404 | UpdatePet422>,
            { petId: UpdatePetPathParams['petId']; data: UpdatePetMutationRequest },
            TContext
        > & { client?: QueryClient }
        client?: Partial<RequestConfig<UpdatePetMutationRequest>> & { client?: Client }
    } = {},
) {
    const { mutation = {}, client: config = {} } = options ?? {}
    const { client: queryClient, ...mutationOptions } = mutation
    const mutationKey = mutationOptions.mutationKey ?? updatePetMutationKey()

    const baseOptions = updatePetMutationOptions(config) as UseMutationOptions<
        UpdatePetMutationResponse,
        ResponseErrorConfig<UpdatePet404 | UpdatePet422>,
        { petId: UpdatePetPathParams['petId']; data: UpdatePetMutationRequest },
        TContext
    >

    return useMutation<
        UpdatePetMutationResponse,
        ResponseErrorConfig<UpdatePet404 | UpdatePet422>,
        { petId: UpdatePetPathParams['petId']; data: UpdatePetMutationRequest },
        TContext
    >(
        {
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
        },
        queryClient,
    ) as UseMutationResult<
        UpdatePetMutationResponse,
        ResponseErrorConfig<UpdatePet404 | UpdatePet422>,
        { petId: UpdatePetPathParams['petId']; data: UpdatePetMutationRequest },
        TContext
    >
}
