export {
    fakeCreatePet,
    fakeCreatePetRequest,
    fakeCreatePetResponse201,
    fakeCreatePetResponse422,
    fakeDeletePetRequest,
    fakeDeletePetResponse404,
    fakeFindPetsByStatusRequest,
    fakeFindPetsByStatusResponse200,
    fakeFindPetsByStatusResponse422,
    fakeGetPetByIdRequest,
    fakeGetPetByIdResponse200,
    fakeGetPetByIdResponse404,
    fakePet,
    fakePetPage,
    fakePetStatus,
    fakeProblem,
    fakeUpdatePet,
    fakeUpdatePetRequest,
    fakeUpdatePetResponse200,
    fakeUpdatePetResponse404,
    fakeUpdatePetResponse422,
} from './codegen/@faker-js/faker.gen'
export type { Options } from './codegen/@faker-js/faker.gen'
