typecheck:
    stage: build
    image: node:24-slim
    cache:
        key:
            files:
                - package-lock.json
        paths:
            - .npm/
    before_script:
        - npm ci --cache .npm --prefer-offline
    script:
        - npm run tsc

build:
    stage: build
    image: node:24-slim
    cache:
        key:
            files:
                - package-lock.json
        paths:
            - .npm/
            - .next/cache/
    before_script:
        - npm ci --cache .npm --prefer-offline
        - cp .env.example .env
        - sh .gitlab/env.sh
    script:
        - npm run build
    artifacts:
        paths:
            - .next/standalone/
            - .next/static/
        expire_in: 1 hour
