#!/bin/sh
sed -i "s|APP_NAME=.*|APP_NAME=$APP_NAME|g" .env
sed -i "s|APP_ENV=.*|APP_ENV=$APP_ENV|g" .env
sed -i "s|FRONT_HOST=.*|FRONT_HOST=$FRONT_HOST|g" .env
sed -i "s|FRONT_PORT=.*|FRONT_PORT=$FRONT_PORT|g" .env
sed -i "s|BACK_INTERNAL_URL=.*|BACK_INTERNAL_URL=$BACK_INTERNAL_URL|g" .env
sed -i "s|HTTP_AUTH_LOGIN=.*|HTTP_AUTH_LOGIN=$HTTP_AUTH_LOGIN|g" .env
sed -i "s|HTTP_AUTH_PASS=.*|HTTP_AUTH_PASS=$HTTP_AUTH_PASS|g" .env
sed -i "s|SENTRY_DSN=.*|SENTRY_DSN=$SENTRY_DSN|g" .env
sed -i "s|SENTRY_AUTH_TOKEN=.*|SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN|g" .env
sed -i "s|SENTRY_ORG=.*|SENTRY_ORG=$SENTRY_ORG|g" .env
sed -i "s|SENTRY_URL=.*|SENTRY_URL=$SENTRY_URL|g" .env
sed -i "s|CI=.*|CI=$CI|g" .env

sed -i "s|NEXT_PUBLIC_APP_ENV=.*|NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV|g" .env
sed -i "s|NEXT_PUBLIC_FRONT_URL=.*|NEXT_PUBLIC_FRONT_URL=$NEXT_PUBLIC_FRONT_URL|g" .env
sed -i "s|NEXT_PUBLIC_BFF_PATH=.*|NEXT_PUBLIC_BFF_PATH=$NEXT_PUBLIC_BFF_PATH|g" .env
sed -i "s|NEXT_PUBLIC_BACK_URL=.*|NEXT_PUBLIC_BACK_URL=$NEXT_PUBLIC_BACK_URL|g" .env
sed -i "s|NEXT_PUBLIC_SENTRY_DSN=.*|NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN|g" .env
