/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { createPetSchema } from '../createPetSchema'
import { petSchema } from '../petSchema'
import { problemSchema } from '../problemSchema'

/** The created pet. */
export const createPet201Schema = z.lazy(() => petSchema)

export type CreatePet201Schema = z.infer<typeof createPet201Schema>

/** The request does not satisfy the contract. */
export const createPet422Schema = z.lazy(() => problemSchema)

export type CreatePet422Schema = z.infer<typeof createPet422Schema>

export const createPetMutationRequestSchema = z.lazy(() => createPetSchema)

export type CreatePetMutationRequestSchema = z.infer<typeof createPetMutationRequestSchema>

export const createPetMutationResponseSchema = z.lazy(() => createPet201Schema)

export type CreatePetMutationResponseSchema = z.infer<typeof createPetMutationResponseSchema>
