/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { problemSchema } from '../problemSchema'

export const deletePetPathParamsSchema = z.object({
    petId: z.string().check(z.minLength(1)),
})

export type DeletePetPathParamsSchema = z.infer<typeof deletePetPathParamsSchema>

/** The pet was deleted. */
export const deletePet204Schema = z.unknown()

export type DeletePet204Schema = z.infer<typeof deletePet204Schema>

/** The requested pet does not exist. */
export const deletePet404Schema = z.lazy(() => problemSchema)

export type DeletePet404Schema = z.infer<typeof deletePet404Schema>

export const deletePetMutationResponseSchema = z.lazy(() => deletePet204Schema)

export type DeletePetMutationResponseSchema = z.infer<typeof deletePetMutationResponseSchema>
