/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { petPageSchema } from '../petPageSchema'
import { petStatusSchema } from '../petStatusSchema'
import { problemSchema } from '../problemSchema'

export const findPetsByStatusQueryParamsSchema = z.object({
    get status() {
        return z.optional(
            z.array(petStatusSchema).check(
                z.refine((items) => new Set(items).size === items.length, {
                    message: 'Array entries must be unique',
                }),
            ),
        )
    },
    offset: z.int().check(z.minimum(0)),
    limit: z.int().check(z.minimum(1), z.maximum(100)),
})

export type FindPetsByStatusQueryParamsSchema = z.infer<typeof findPetsByStatusQueryParamsSchema>

/** One page of pets. */
export const findPetsByStatus200Schema = z.lazy(() => petPageSchema)

export type FindPetsByStatus200Schema = z.infer<typeof findPetsByStatus200Schema>

/** The request does not satisfy the contract. */
export const findPetsByStatus422Schema = z.lazy(() => problemSchema)

export type FindPetsByStatus422Schema = z.infer<typeof findPetsByStatus422Schema>

export const findPetsByStatusQueryResponseSchema = z.lazy(() => findPetsByStatus200Schema)

export type FindPetsByStatusQueryResponseSchema = z.infer<
    typeof findPetsByStatusQueryResponseSchema
>
