/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { petSchema } from '../petSchema'
import { problemSchema } from '../problemSchema'

export const getPetByIdPathParamsSchema = z.object({
    petId: z.string().check(z.minLength(1)),
})

export type GetPetByIdPathParamsSchema = z.infer<typeof getPetByIdPathParamsSchema>

/** The requested pet. */
export const getPetById200Schema = z.lazy(() => petSchema)

export type GetPetById200Schema = z.infer<typeof getPetById200Schema>

/** The requested pet does not exist. */
export const getPetById404Schema = z.lazy(() => problemSchema)

export type GetPetById404Schema = z.infer<typeof getPetById404Schema>

export const getPetByIdQueryResponseSchema = z.lazy(() => getPetById200Schema)

export type GetPetByIdQueryResponseSchema = z.infer<typeof getPetByIdQueryResponseSchema>
