/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { petSchema } from '../petSchema'
import { problemSchema } from '../problemSchema'
import { updatePetSchema } from '../updatePetSchema'

export const updatePetPathParamsSchema = z.object({
    petId: z.string().check(z.minLength(1)),
})

export type UpdatePetPathParamsSchema = z.infer<typeof updatePetPathParamsSchema>

/** The updated pet. */
export const updatePet200Schema = z.lazy(() => petSchema)

export type UpdatePet200Schema = z.infer<typeof updatePet200Schema>

/** The requested pet does not exist. */
export const updatePet404Schema = z.lazy(() => problemSchema)

export type UpdatePet404Schema = z.infer<typeof updatePet404Schema>

/** The request does not satisfy the contract. */
export const updatePet422Schema = z.lazy(() => problemSchema)

export type UpdatePet422Schema = z.infer<typeof updatePet422Schema>

export const updatePetMutationRequestSchema = z.lazy(() => updatePetSchema)

export type UpdatePetMutationRequestSchema = z.infer<typeof updatePetMutationRequestSchema>

export const updatePetMutationResponseSchema = z.lazy(() => updatePet200Schema)

export type UpdatePetMutationResponseSchema = z.infer<typeof updatePetMutationResponseSchema>
