// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeGetRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/(home)/page.info";
import * as ApiFeatureFlagRoute from "@/api/feature-flag/route.info";
import * as ApiHealthRoute from "@/api/health/route.info";

export const Home = makeRoute(
  "/(home)",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);

export const getApiFeatureFlag = makeGetRoute(
  "/api/feature-flag",
  {
    ...defaultInfo,
    ...ApiFeatureFlagRoute.Route
  },
  ApiFeatureFlagRoute.GET
);
export const getApiHealth = makeGetRoute(
  "/api/health",
  {
    ...defaultInfo,
    ...ApiHealthRoute.Route
  },
  ApiHealthRoute.GET
);
