// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod';
import { makeGetRoute, makeRoute } from './makeRoute';

const defaultInfo = {
    search: z.object({}),
};

import * as HomeRoute from '@/(home)/page.info';
import * as HomeUiDemoRoute from '@/(home)/ui-demo/page.info';
import * as ApiHealthRoute from '@/api/health/route.info';
import * as ApiMetricsRoute from '@/api/metrics/route.info';
import * as ApiReadyRoute from '@/api/ready/route.info';

export const Home = makeRoute('/(home)', {
    ...defaultInfo,
    ...HomeRoute.Route,
});
export const HomeUiDemo = makeRoute('/(home)/ui-demo', {
    ...defaultInfo,
    ...HomeUiDemoRoute.Route,
});

export const getApiHealth = makeGetRoute(
    '/api/health',
    {
        ...defaultInfo,
        ...ApiHealthRoute.Route,
    },
    ApiHealthRoute.GET
);
export const getApiMetrics = makeGetRoute(
    '/api/metrics',
    {
        ...defaultInfo,
        ...ApiMetricsRoute.Route,
    },
    ApiMetricsRoute.GET
);
export const getApiReady = makeGetRoute(
    '/api/ready',
    {
        ...defaultInfo,
        ...ApiReadyRoute.Route,
    },
    ApiReadyRoute.GET
);
