/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { CreatePet } from '../CreatePet'
import type { Pet } from '../Pet'
import type { Problem } from '../Problem'

/** The created pet. */
export type CreatePet201 = Pet

/** The request does not satisfy the contract. */
export type CreatePet422 = Problem

export type CreatePetMutationRequest = CreatePet

export type CreatePetMutationResponse = CreatePet201

export type CreatePetMutation = {
    Response: CreatePet201
    Request: CreatePetMutationRequest
    Errors: CreatePet422
}
