/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Problem } from '../Problem'

export type DeletePetPathParams = {
    /**
     * Stable pet identifier.
     *
     * @type string
     * @minLength 1
     */
    petId: string
}

/** The pet was deleted. */
export type DeletePet204 = unknown

/** The requested pet does not exist. */
export type DeletePet404 = Problem

export type DeletePetMutationResponse = DeletePet204

export type DeletePetMutation = {
    Response: DeletePet204
    PathParams: DeletePetPathParams
    Errors: DeletePet404
}
