/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { PetPage } from '../PetPage'
import type { PetStatus } from '../PetStatus'
import type { Problem } from '../Problem'

export type FindPetsByStatusQueryParams = {
    /**
     * Return pets matching any supplied status.
     *
     * @type array | undefined
     */
    status?: PetStatus[]
    /**
     * Zero-based collection offset.
     *
     * @default 0
     * @type integer | undefined
     * @minLength 0
     */
    offset?: number
    /**
     * Maximum number of pets returned in one page.
     *
     * @default 20
     * @type integer | undefined
     * @minLength 1
     * @maxLength 100
     */
    limit?: number
}

/** One page of pets. */
export type FindPetsByStatus200 = PetPage

/** The request does not satisfy the contract. */
export type FindPetsByStatus422 = Problem

export type FindPetsByStatusQueryResponse = FindPetsByStatus200

export type FindPetsByStatusQuery = {
    Response: FindPetsByStatus200
    QueryParams: FindPetsByStatusQueryParams
    Errors: FindPetsByStatus422
}
