/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Pet } from '../Pet'
import type { Problem } from '../Problem'

export type GetPetByIdPathParams = {
    /**
     * Stable pet identifier.
     *
     * @type string
     * @minLength 1
     */
    petId: string
}

/** The requested pet. */
export type GetPetById200 = Pet

/** The requested pet does not exist. */
export type GetPetById404 = Problem

export type GetPetByIdQueryResponse = GetPetById200

export type GetPetByIdQuery = {
    Response: GetPetById200
    PathParams: GetPetByIdPathParams
    Errors: GetPetById404
}
