/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Pet } from '../Pet'
import type { Problem } from '../Problem'
import type { UpdatePet } from '../UpdatePet'

export type UpdatePetPathParams = {
    /**
     * Stable pet identifier.
     *
     * @type string
     * @minLength 1
     */
    petId: string
}

/** The updated pet. */
export type UpdatePet200 = Pet

/** The requested pet does not exist. */
export type UpdatePet404 = Problem

/** The request does not satisfy the contract. */
export type UpdatePet422 = Problem

export type UpdatePetMutationRequest = UpdatePet

export type UpdatePetMutationResponse = UpdatePet200

export type UpdatePetMutation = {
    Response: UpdatePet200
    Request: UpdatePetMutationRequest
    PathParams: UpdatePetPathParams
    Errors: UpdatePet404 | UpdatePet422
}
