/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    CreatePetMutationRequest,
    CreatePetMutationResponse,
    CreatePet422,
} from '../../models/petsController/CreatePet'

import fetch from '../../../fetch.client'
import {
    createPetMutationResponseSchema,
    createPetMutationRequestSchema,
} from '../../zod/petsController/createPetSchema'

function getCreatePetUrl() {
    const res = { method: 'POST', url: `/pets` as const }
    return res
}

/**
 * Adds one pet to the example catalog.
 *
 * @summary Create a pet
 * {@link /pets}
 */
export async function createPet(
    { data }: { data: CreatePetMutationRequest },
    config: Partial<RequestConfig<CreatePetMutationRequest>> & { client?: Client } = {},
) {
    const { client: request = fetch, ...requestConfig } = config

    const requestData = createPetMutationRequestSchema.parse(data)

    const res = await request<
        CreatePetMutationResponse,
        ResponseErrorConfig<CreatePet422>,
        CreatePetMutationRequest
    >({
        method: 'POST',
        url: getCreatePetUrl().url.toString(),
        data: requestData,
        ...requestConfig,
    })
    return createPetMutationResponseSchema.parse(res.data)
}
