/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    DeletePetMutationResponse,
    DeletePetPathParams,
    DeletePet404,
} from '../../models/petsController/DeletePet'

import fetch from '../../../fetch.client'
import { deletePetMutationResponseSchema } from '../../zod/petsController/deletePetSchema'

function getDeletePetUrl({ petId }: { petId: DeletePetPathParams['petId'] }) {
    const res = { method: 'DELETE', url: `/pets/${petId}` as const }
    return res
}

/**
 * Removes one pet from the example catalog.
 *
 * @summary Delete a pet
 * {@link /pets/:petId}
 */
export async function deletePet(
    { petId }: { petId: DeletePetPathParams['petId'] },
    config: Partial<RequestConfig> & { client?: Client } = {},
) {
    const { client: request = fetch, ...requestConfig } = config

    const res = await request<
        DeletePetMutationResponse,
        ResponseErrorConfig<DeletePet404>,
        unknown
    >({ method: 'DELETE', url: getDeletePetUrl({ petId }).url.toString(), ...requestConfig })
    return deletePetMutationResponseSchema.parse(res.data)
}
