/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    FindPetsByStatusQueryResponse,
    FindPetsByStatusQueryParams,
    FindPetsByStatus422,
} from '../../models/petsController/FindPetsByStatus'

import fetch from '../../../fetch.client'
import { findPetsByStatusQueryResponseSchema } from '../../zod/petsController/findPetsByStatusSchema'

function getFindPetsByStatusUrl() {
    const res = { method: 'GET', url: `/pets` as const }
    return res
}

/**
 * Returns one offset-based page of pets, optionally filtered by status.
 *
 * @summary Find pets by status
 * {@link /pets}
 */
export async function findPetsByStatus(
    { params }: { params?: FindPetsByStatusQueryParams } = {},
    config: Partial<RequestConfig> & { client?: Client } = {},
) {
    const { client: request = fetch, ...requestConfig } = config

    const res = await request<
        FindPetsByStatusQueryResponse,
        ResponseErrorConfig<FindPetsByStatus422>,
        unknown
    >({ method: 'GET', url: getFindPetsByStatusUrl().url.toString(), params, ...requestConfig })
    return findPetsByStatusQueryResponseSchema.parse(res.data)
}
