/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    GetPetByIdQueryResponse,
    GetPetByIdPathParams,
    GetPetById404,
} from '../../models/petsController/GetPetById'

import fetch from '../../../fetch.client'
import { getPetByIdQueryResponseSchema } from '../../zod/petsController/getPetByIdSchema'

function getGetPetByIdUrl({ petId }: { petId: GetPetByIdPathParams['petId'] }) {
    const res = { method: 'GET', url: `/pets/${petId}` as const }
    return res
}

/**
 * Returns one pet by its stable identifier.
 *
 * @summary Get a pet
 * {@link /pets/:petId}
 */
export async function getPetById(
    { petId }: { petId: GetPetByIdPathParams['petId'] },
    config: Partial<RequestConfig> & { client?: Client } = {},
) {
    const { client: request = fetch, ...requestConfig } = config

    const res = await request<GetPetByIdQueryResponse, ResponseErrorConfig<GetPetById404>, unknown>(
        { method: 'GET', url: getGetPetByIdUrl({ petId }).url.toString(), ...requestConfig },
    )
    return getPetByIdQueryResponseSchema.parse(res.data)
}
