/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../fetch.client'
import type {
    UpdatePetMutationRequest,
    UpdatePetMutationResponse,
    UpdatePetPathParams,
    UpdatePet404,
    UpdatePet422,
} from '../../models/petsController/UpdatePet'

import fetch from '../../../fetch.client'
import {
    updatePetMutationResponseSchema,
    updatePetMutationRequestSchema,
} from '../../zod/petsController/updatePetSchema'

function getUpdatePetUrl({ petId }: { petId: UpdatePetPathParams['petId'] }) {
    const res = { method: 'PATCH', url: `/pets/${petId}` as const }
    return res
}

/**
 * Partially updates the name or status of one pet.
 *
 * @summary Update a pet
 * {@link /pets/:petId}
 */
export async function updatePet(
    { petId, data }: { petId: UpdatePetPathParams['petId']; data: UpdatePetMutationRequest },
    config: Partial<RequestConfig<UpdatePetMutationRequest>> & { client?: Client } = {},
) {
    const { client: request = fetch, ...requestConfig } = config

    const requestData = updatePetMutationRequestSchema.parse(data)

    const res = await request<
        UpdatePetMutationResponse,
        ResponseErrorConfig<UpdatePet404 | UpdatePet422>,
        UpdatePetMutationRequest
    >({
        method: 'PATCH',
        url: getUpdatePetUrl({ petId }).url.toString(),
        data: requestData,
        ...requestConfig,
    })
    return updatePetMutationResponseSchema.parse(res.data)
}
