// This file is auto-generated by @hey-api/openapi-ts

import type {
    CreatePet,
    CreatePet2,
    CreatePetData,
    CreatePetErrors,
    CreatePetResponses,
    DeletePetData,
    DeletePetErrors,
    FindPetsByStatusData,
    FindPetsByStatusErrors,
    FindPetsByStatusResponses,
    GetPetByIdData,
    GetPetByIdErrors,
    GetPetByIdResponses,
    Limit,
    Limit2,
    Offset,
    Offset2,
    Pet,
    Pet2,
    PetId,
    PetId2,
    PetPage,
    PetPage2,
    PetStatus,
    PetStatus2,
    PetStatus3,
    PetStatusFilter,
    Problem,
    Problem2,
    UpdatePet,
    UpdatePet2,
    UpdatePetData,
    UpdatePetErrors,
    UpdatePetResponses,
} from '../types.gen'

import { faker, type Faker } from '@faker-js/faker'

export type Options = {
    faker?: Faker
    /**
     * Whether to include optional properties, including add property to record object. Provide a
     * number between 0 and 1 to randomly include based on that probability.
     *
     * @default true
     */
    includeOptional?: boolean | number
    /**
     * Whether to use schema default values instead of generating fake data. Provide a number
     * between 0 and 1 to randomly use defaults based on that probability.
     *
     * @default false
     */
    useDefault?: boolean | number
}

const resolveCondition = (condition: boolean | number, faker: Faker): boolean =>
    condition === true ||
    (typeof condition === 'number' && faker.datatype.boolean({ probability: condition }))

export const fakePetStatus = (options?: Options): PetStatus3 => {
    const f = options?.faker ?? faker
    return f.helpers.arrayElement(['available', 'pending', 'sold'])
}

export const fakePetStatus2 = (options?: Options): PetStatus => fakePetStatus(options)

export const fakePet = (options?: Options): Pet2 => {
    const f = options?.faker ?? faker
    return {
        id: f.string.uuid(),
        name: f.string.alpha({ length: { min: 1, max: 120 } }),
        status: fakePetStatus(options),
        createdAt: f.date.recent().toISOString(),
    }
}

export const fakePet2 = (options?: Options): Pet => fakePet(options)

export const fakePetPage = (options?: Options): PetPage2 => {
    const f = options?.faker ?? faker
    return {
        items: f.helpers.multiple(() => fakePet(options)),
        offset: f.number.int({ min: 0 }),
        limit: f.number.int({ min: 1, max: 100 }),
        total: f.number.int({ min: 0 }),
    }
}

export const fakePetPage2 = (options?: Options): PetPage => fakePetPage(options)

export const fakeProblem = (options?: Options): Problem2 => {
    const f = options?.faker ?? faker
    return {
        status: f.number.int({ min: 400, max: 599 }),
        code: f.string.alpha({ length: { min: 1, max: 100 } }),
        title: f.lorem.words(),
        ...(!resolveCondition(options?.includeOptional ?? true, f)
            ? {}
            : { detail: f.string.sample() }),
    }
}

export const fakeProblem2 = (options?: Options): Problem => fakeProblem(options)

export const fakeCreatePet = (options?: Options): CreatePet2 => {
    const f = options?.faker ?? faker
    return {
        name: f.string.alpha({ length: { min: 1, max: 120 } }),
        ...(!resolveCondition(options?.includeOptional ?? true, f)
            ? {}
            : { status: fakePetStatus(options) }),
    }
}

export const fakeCreatePet2 = (options?: Options): CreatePet => fakeCreatePet(options)

export const fakeUpdatePet = (options?: Options): UpdatePet2 => {
    const f = options?.faker ?? faker
    return {
        ...(!resolveCondition(options?.includeOptional ?? true, f)
            ? {}
            : { name: f.string.alpha({ length: { min: 1, max: 120 } }) }),
        ...(!resolveCondition(options?.includeOptional ?? true, f)
            ? {}
            : { status: fakePetStatus(options) }),
    }
}

export const fakeUpdatePet2 = (options?: Options): UpdatePet => fakeUpdatePet(options)

export const fakePetId = (options?: Options): PetId => {
    const f = options?.faker ?? faker
    return f.string.alpha({ length: { min: 1, max: 100 } })
}

export const fakePetStatusFilter = (options?: Options): PetStatusFilter => {
    const f = options?.faker ?? faker
    return f.helpers.multiple(() => fakePetStatus(options))
}

export const fakeOffset = (options?: Options): Offset => {
    const f = options?.faker ?? faker
    return resolveCondition(options?.useDefault ?? false, f) ? 0 : f.number.int({ min: 0 })
}

export const fakeLimit = (options?: Options): Limit => {
    const f = options?.faker ?? faker
    return resolveCondition(options?.useDefault ?? false, f)
        ? 20
        : f.number.int({ min: 1, max: 100 })
}

export const fakePetStatus3 = (options?: Options): PetStatus2 => {
    const f = options?.faker ?? faker
    return f.helpers.multiple(() => fakePetStatus(options))
}

export const fakeOffset2 = (options?: Options): Offset2 => {
    const f = options?.faker ?? faker
    return resolveCondition(options?.useDefault ?? false, f) ? 0 : f.number.int({ min: 0 })
}

export const fakeLimit2 = (options?: Options): Limit2 => {
    const f = options?.faker ?? faker
    return resolveCondition(options?.useDefault ?? false, f)
        ? 20
        : f.number.int({ min: 1, max: 100 })
}

export const fakePetId2 = (options?: Options): PetId2 => {
    const f = options?.faker ?? faker
    return f.string.alpha({ length: { min: 1, max: 100 } })
}

export const fakeFindPetsByStatusRequest = (
    options?: Options,
): Omit<FindPetsByStatusData, 'url'> => {
    const f = options?.faker ?? faker
    return {
        query: {
            ...(!resolveCondition(options?.includeOptional ?? true, f)
                ? {}
                : { status: f.helpers.multiple(() => fakePetStatus(options)) }),
            ...(!resolveCondition(options?.includeOptional ?? true, f)
                ? {}
                : {
                      offset: resolveCondition(options?.useDefault ?? false, f)
                          ? 0
                          : f.number.int({ min: 0 }),
                  }),
            ...(!resolveCondition(options?.includeOptional ?? true, f)
                ? {}
                : {
                      limit: resolveCondition(options?.useDefault ?? false, f)
                          ? 20
                          : f.number.int({ min: 1, max: 100 }),
                  }),
        },
    }
}

export const fakeFindPetsByStatusResponse200 = (
    options?: Options,
): FindPetsByStatusResponses[200] => fakePetPage(options)

export const fakeFindPetsByStatusResponse422 = (options?: Options): FindPetsByStatusErrors[422] =>
    fakeProblem(options)

export const fakeCreatePetRequest = (options?: Options): Omit<CreatePetData, 'url'> => ({
    body: fakeCreatePet(options),
})

export const fakeCreatePetResponse201 = (options?: Options): CreatePetResponses[201] =>
    fakePet(options)

export const fakeCreatePetResponse422 = (options?: Options): CreatePetErrors[422] =>
    fakeProblem(options)

export const fakeDeletePetRequest = (options?: Options): Omit<DeletePetData, 'url'> => {
    const f = options?.faker ?? faker
    return {
        path: {
            petId: f.string.uuid(),
        },
    }
}

export const fakeDeletePetResponse404 = (options?: Options): DeletePetErrors[404] =>
    fakeProblem(options)

export const fakeGetPetByIdRequest = (options?: Options): Omit<GetPetByIdData, 'url'> => {
    const f = options?.faker ?? faker
    return {
        path: {
            petId: f.string.uuid(),
        },
    }
}

export const fakeGetPetByIdResponse200 = (options?: Options): GetPetByIdResponses[200] =>
    fakePet(options)

export const fakeGetPetByIdResponse404 = (options?: Options): GetPetByIdErrors[404] =>
    fakeProblem(options)

export const fakeUpdatePetRequest = (options?: Options): Omit<UpdatePetData, 'url'> => {
    const f = options?.faker ?? faker
    return {
        body: fakeUpdatePet(options),
        path: {
            petId: f.string.uuid(),
        },
    }
}

export const fakeUpdatePetResponse200 = (options?: Options): UpdatePetResponses[200] =>
    fakePet(options)

export const fakeUpdatePetResponse404 = (options?: Options): UpdatePetErrors[404] =>
    fakeProblem(options)

export const fakeUpdatePetResponse422 = (options?: Options): UpdatePetErrors[422] =>
    fakeProblem(options)
